name: HyperingEconomyGUI
main: amata1219.hypering.economy.gui.HyperingEconomyGUI
version: 1.0.0
api-version: 1.13
depend: [HyperingEconomy, HogochiByebye, Votifier, CrazyAuctions]
author: amata1219(Twitter@amata1219)

commands:
  g:
    description: main command.
    usage: /<command>
    aliases: gui
    permission: hypering.economy.gui.g
    permission-message: You do not have permission(<permission>).
  d:
    description: anti ghost blocks.
    usage: /<command>
    permission: hypering.economy.gui.d
    permission-message: You do not have permission(<permission>).
  heg:
    description: admin command.
    usage: /<command>
    permission: hypering.economy.gui.heg
    permission-message: You do not have permission(<permission>).