name: HyperingEconomyGUI
main: amata1219.hypering.economy.gui.HyperingEconomyGUI
version: 1.0.0
depend: [HyperingEconomy, HogochiByebye, Votifier, CrazyAuctions]
author: amata1219(Twitter@amata1219)

commands:
  g:
    description: main command.
    usage: /<command>
    permission: hypering.economy.gui.g
    permission-message: You do not have permission(<permission>).
  hegreload:
    description: reload command.
    usage: /<command>
    permission: hypering.economy.gui.greload
    permission-message: You do not have permission(<permission>).