package amata1219.hypering.economy.gui.util;

public enum Case {

	SEND_MONEY,
	BUY_TICKET,
	CASH_TICKET,
	BUY_HOGOCHI,
	SELL_HOGOCHI,
	WITHDRAW_HOGOCHI_SALE,
	FLATTEN_HOGOCHI,
	CONFIRMATION_FLATTEN_HOGOCHI,
	COMBINE_HOGOCHIES,
	SPLIT_HOGOCHI;

}
